### ISSUE TITLE
Fix repo layout

### ISSUE THREAD

**Issue by kormat** [netsec-ethz/scion#1007]
The current repository layout has a number of problems:

- none of the code in `endhost/` is specific to endhosts.
- `infrastructure/scion_elem.py` is used by all scion python applications, not just infrastructure.
- `lib/` contains python code. Oh, except for `lib/libscion`, `lib/libhsr`, `lib/libfilter`, which are all C.

The top-level categories don't make sense, languages are mixed, and it's unclear where to find certain parts of the code if you're new to the project.

My proposal to fix this is to change the groupings of code, to use the language as the top-level grouping. Here's how it would look: https://gist.github.com/kormat/0e5e080914b4acd5d2edb960574d04f7

Note that the location of tests is language-specific. Go puts tests in the same dir as the code, C puts tests in a sub-directory, and python groups all tests under `python/tests/` like we do currently. Tests which aren't language-specific go instead into the top-level `tests/` dir, like end2end does.

**Comment by kormat** [comment]
This will make the codebase a lot more maintainable in the future, but is a large amount of work, and will break any in-flight changes that people are working on, so it needs careful coordination to pull off. As @shitz pointed out, the later we leave this the harder it will be to do, so sooner is definitely better.

**Comment by shitz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change layout of github repository](https://trello.com/c/jAC7cpXA/10-change-layout-of-github-repository)

**Comment by kormat** [comment]
Implemented by #1118.
