### ISSUE TITLE
Certificate servers need to use paths to fetch TRCs/Certs

### ISSUE THREAD

**Issue by klausman** [netsec-ethz/scion#1013]
Currently, we still do the pathless lookup which doesn't work anymore.

After [PR1010](https://reviewable.io/reviews/netsec-ethz/scion/1010) is merged, the certificate server at least has the ability to look up paths. But we still need to fix (at least) `_fetch_trc()` to then actually use that information to fetch certificates.

The current situation results in beacon servers killing the CS as soon as they request a missing cert.

**Comment by kormat** [comment]
Clarification - the crash is fixed by #1014. Cert/TRC lookup is still broken for the reasons mentioned above (pathless requests aren't supported any more).

**Comment by Oncilla** [comment]
Addressed by PR #1087
