### ISSUE TITLE
retry path segment verification

### ISSUE THREAD

**Issue by kormat** [netsec-ethz/scion#1079]
Currently if an element has a path segment it wants to verify but is missing trcs/certs, it will send requests for the missing trcs/certs once, but never again. If it doesn't get answers, then it will keep the pending path segments around indefinitely.

**Comment by shitz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Retry path segment verification](https://trello.com/c/GvIa2Yi6/9-retry-path-segment-verification)

**Comment by shitz** [comment]
Implement with #1121
