### ISSUE TITLE
Change CPS propagation queues to expiring dicts

### ISSUE THREAD

**Issue by kormat** [netsec-ethz/scion#1126]
Currently when a non-master CPS gets a down-segment registration (https://github.com/netsec-ethz/scion/blob/8773e206f4529168145edb273f56c90498ad3007/python/path_server/core.py#L110) it adds it to a deque for propagation to other core ASes. But as it is not master, that queue is never serviced, and grows continuously. If we replace this deque with an expiring dict instead, using the pcb ID as the key, this would both remove the unbounded queuing behaviour, as well as remove duplicate propagations.

The deque for propagating core PCBs to the master CPS probably also needs the same treatment, as if the connection to zookeeper breaks, that queue doesn't get cleared either.

**Comment by shitz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[1] Change CPS propagation queues to expiring dicts](https://trello.com/c/7jGuTIah/24-1-change-cps-propagation-queues-to-expiring-dicts)
