### ISSUE TITLE
afpacket.go missing variables on 32bit ARM

### ISSUE THREAD

**Issue by hausheer** [netsec-ethz/scion#1261]
As discussed with @perrig afpacket.go is missing the unix.PACKET_VERSION and unix.PACKET_FANOUT variables under ARM 32bit architectures (e.g. Odroid/RaspberryPi)

The problem can be temporarily fixed with the following workaround:

sed -ie 's/unix.PACKET_VERSION/0xa/g'
go/vendor/github.com/google/gopacket/afpacket/afpacket.go
sed -ie 's/unix.PACKET_FANOUT/0x12/g'
go/vendor/github.com/google/gopacket/afpacket/afpacket.go

cd go
go install ./vendor/...
cp vendor/zombiezen.com/go/capnproto2/std/go.capnp ../proto/go.capnp 
cd ..

**Comment by hausheer** [comment]
@perrig I raised an issue on that

**Comment by kormat** [comment]
The problem is not with `gopacket`, it's that the version of `golang.org/x/sys/unix` we're using is old, and doesn't contain the relevant constants for 32bit arm. Sending a PR to update it.

**Comment by kormat** [comment]
This should be fixed now, please test, and re-open this bug if it isn't. Thanks.

**Comment by hausheer** [comment]
Yes it works, thanks!
