### ISSUE TITLE
sciond api

### ISSUE THREAD

**Issue by pszalach** [netsec-ethz/scion#408]
Current API needs to be revised.
I propose the following:

**Path(s) request:**
`\x00 (1B) | ISD (12bits) | AS (20bits)`
Reply:
`path_len0 (1B) | path0 (path_len0*8B) | mtu0 (2B) | path_len1 ...`

**Name resolution request:**
`\x01 (1B) | domain-name (variable)`
Reply:
`ISD (12bits) | AS (20bits) | addr_type0 (1B) | addr0 (var) | addr_type1...`

**iface request:**
`\x02 (1B)`
Reply:
`if_id0 (2B) | addr_type0 (1B) | addr0 (var) | id_id1 ...`  

Do we need something more at this point?
As there should be one sciond per host, we need also to consider how to handle multihomimg.

**Comment by kormat** [comment]
Closing in favour of #986.
