### ISSUE TITLE
Huge PCBs

### ISSUE THREAD

**Issue by pszalach** [netsec-ethz/scion#474]
Something to think about (long-term):
Some ASes have huge numbers of peering links: e.g. google has ~6K peers as reported recently [1].
An entry for such an AS would take above 250KB. Without revocation tokens the same entry would be about 70KB. 
In both cases PCB would exceed max packet size. Although it is not a problem as we will have an UDP with ACKs for control plane, the registration, storage, and lookup may be resource consuming (seems that caching may be really important).
We could also think about splitting big PCBs while propagating/registering, but it influences a lot...

[1] http://conferences2.sigcomm.org/imc/2015/papers/p523.pdf

**Comment by kormat** [comment]
This is covered by using TCP for propagation, combined with the new revocation system which has a constant (and small) PCB overhead.
