### ISSUE TITLE
Multi-network-interface (wifi + LTE etc) support

### ISSUE THREAD

**Issue by aznair** [netsec-ethz/scion#534]
This is probably not for 0.1, maybe not even 0.2 but I'd like to put it out there before I forget again.

We need to decide how to handle multiple network interfaces on a single host.
1. SCIOND handles multiple address/ISD_AD associations
2. SCIOND instance per interface
3. Something else

**Comment by kormat** [comment]
With the new SCIOND api (#1002), both 1) and 2) should be supportable. I would tend towards 1) for now.
