### ISSUE TITLE
Revocation not being sent to core

### ISSUE THREAD

**Issue by ShantanuThakoor** [netsec-ethz/scion#810]
Currently, revocation is only sent back along the path traversed by the packet that was to be sent on the revoked link.
The problem is, this path may not contain a core AS.

In such a case, the endhost that was sending the packet will remove the path from its local cache. However, if it tries to send a packet to the same destination again, it will ask its core AS for paths to it, and will get the same path again (since the core AS did not receive the revocation).
(In default.topo, this would be the case if 2-26 tries to contact 2-25 via 2-23 and the 2-23,2-25 link is down. Revocation would not be sent to 2-21, and when 2-26 wants to contact 2-23 it will get the path again from 2-21).

A possible fix: when issuing revocation, the beacon server also sends revocations to the core ASes of its ISD. To account for revocations across ISDs not going through core ASes due to peering links, any AS receiving a revocation through a non-upstream interface which is also to be forwarded to a non-upstream interfaces, should send the revocations to all the core ASes in its ISD.

**Comment by kormat** [comment]
@shitz - is this fixed now?

**Comment by shitz** [comment]
Fixed via #947
