### ISSUE TITLE
Expiration and revocation bugs

### ISSUE THREAD

**Issue by pszalach** [netsec-ethz/scion#900]
Few problems found after an overnight stress test. The scenario:
- end2end test executed in an infinite loop
- TCP was on, but it seems to be not relevant

1a) after ~12h, a BR received a packet with an expired path
1b) while triggering SCMP msg the BR failed with:
[br1-13-1.txt](https://github.com/netsec-ethz/scion/files/476569/br1-13-1.txt)
2) after another ~3h two PSes failed, handling a revocation:
[ps1-11-1.txt](https://github.com/netsec-ethz/scion/files/476631/ps1-11-1.txt)
[ps1-13-1.txt](https://github.com/netsec-ethz/scion/files/476632/ps1-13-1.txt)

1a) seems like a stale core-path segment cached at some path server.
2) seems like an internal problem of ExpiringDict

**Comment by kormat** [comment]
From discussion:
1b) looks like a `get_first_hop` failure
2) is a ExpiringDict bug, fixed by #901 

I don't know what 1a) is.

**Comment by shitz** [comment]
I think we can close this one. The race condition got fixed and the Python BR got deprecated.
