### ISSUE TITLE
Leap second error(s)?

### ISSUE THREAD

**Issue by pszalach** [netsec-ethz/scion#961]
Some great news from the New Year's Eve:
1) Routers crashed with:
`Panic msg="counter cannot decrease in value"`
https://gist.github.com/pszalach/251efa1b4a20e36a6ab40570d314f31c

2) Then after six hours few BSes died with `raise ZkNoConnection from None`
https://gist.github.com/pszalach/2a972bfa16607deff2aca71fcd44bc33

**Comment by pszalach** [comment]
AFAIR this was tested on `pszalach:tcp_fixes` (not on the master)

**Comment by kormat** [comment]
`1.` is definitely a leap-second. Unfortunately Golang's std library does not provide any way around this. Some research suggests that we can use https://github.com/gavv/monotime to avoid this issue.

`2.` is a bug in the beacon server revocation code that fails to handle the `ZkNoConnection` exception.

**Comment by kormat** [comment]
`1.` is now fixed by #973, `2.` was fixed by #963.
