### ISSUE TITLE
sciond API

### ISSUE THREAD

**Issue by kormat** [netsec-ethz/scion#986]
The current sciond API is hand-coded, and very restricted. We need a new API based on capnp to allow greater freedom of development.

Things to support:
- path requests
- revocation notification
- querying the local ISD-AS id

**Comment by shitz** [comment]
Gist to track the current proposal of the SCIOND API:
https://gist.github.com/shitz/89e613d16039206ba802dd2b32b6cb52

**Comment by pszalach** [comment]
we also may consider adding `exp_time`/`ttl` to `SCIONPath`

**Comment by kormat** [comment]
@shitz - a redesign was discussed ages ago in #408, which has some things that aren't (yet) covered by this design.

**Comment by shitz** [comment]
Ok, so from #408 I think it makes sense to add the following:
1) Including the original request in the response (this could also be a random ID per request)
2) Adding a parameter k to the request
3) Adding error codes?

I think for the current iteration, the name lookup part is not needed, right?

**Comment by kormat** [comment]
#1006 is also merged now. I think that's all the development, now we just need to start removing the deprecated use of a sciond object from within python.

**Comment by shitz** [comment]
Not yet. The `GetBRs` and `GetSVCs` calls need to be implemented, such that we can remove all the `sd.get_first_hop` calls.

**Comment by kormat** [comment]
Missing:
- blacklisting and whitelisting for both ISDs and ASes.

**Comment by shitz** [comment]
I think for the purpose of the pre-production milestone, the SCIOND API is done and this can be closed. We can always open up new issues for feature requests.
