### ISSUE TITLE
Updated topology format

### ISSUE THREAD

**Issue by kormat** [netsec-ethz/scion#987]
The existing topo format has a few problems:

- it's yaml, which is slower to parse than json
- it doesn't account for NAT
- overlay is hardcoded
- doesn't support dual-stack networks

The new format (https://gist.github.com/kormat/188ec38ca6f33e6b6f8e720a88d390db) proposed in #815 will fix these problems.

**Comment by kormat** [comment]
As part of this, https://github.com/netsec-ethz/scion-web/issues/57 is also needed.

**Comment by shitz** [comment]
Fixed by #1116 and #1057
